[tool.poetry]
name = "bgpneiget"
version = "2.0.0"
description = "Get BGP Neighbours from network devices"
authors = ["Rob Woodward <rob@emailplus.org>"]

license = "BSD-2-Clause"
readme = "README.md"
repository = "https://github.com/robwdwd/bgpneiget"
include = ["README.md", "LICENSE"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
scrapli = "^2023.1.30"
asyncssh = "^2.13.1"
textfsm = "^1.1.3"
xmltodict = "^0.13.0"
aiosqlite = "^0.19.0"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
pytest = "^7.1.3"
pylint = "^2.9.6"
pydocstyle = "^6.1.1"
flake8 = "^6.0.0"
isort = "^5.12.0"

[tool.poetry.scripts]
bgpneiget = "bgpneiget.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
